//
//  ZerkImportTests.swift
//  Zerk
//

import SwiftParser
import Testing
@testable import CodegenToolkit

/// Coverage of `#ZerkImport`, which is the only way a generated file can see a
/// name from outside the module.
///
/// The generated file imports `Zerk` and nothing else, because the plugin reads
/// syntax and cannot tell which module a name came from. That holds while every
/// type in the graph is local and fails the moment one is not — a provider
/// parameter typed `Date` emits into a file where `Date` does not exist.
@Suite("#ZerkImport")
struct ZerkImportTests {

    @Test("a requested module is imported")
    func requestedModuleIsImported() {
        let source = """
        #ZerkImport(module: "Foundation")

        @Injectable
        struct Stamp {
            @InjectableProviding
            init(at: Date) {}
        }
        """

        let result = CompileFixture.generateWithResolution(source: source)

        #expect(result.output.output.contains("import Zerk\nimport Foundation\n"))
    }

    @Test("modules are deduplicated and sorted across every occurrence")
    func modulesAreDeduplicatedAndSorted() {
        // Order and repetition in the source must not change the output, or the
        // generated file churns between builds.
        let source = """
        #ZerkImport(module: "Foundation")
        #ZerkImport(module: "CoreLocation", "Foundation")

        @Injectable
        struct Stamp {
            @InjectableProviding
            init() {}
        }
        """

        let result = CompileFixture.generateWithResolution(source: source)

        #expect(result.output.output.contains("import Zerk\nimport CoreLocation\nimport Foundation\n"))
    }

    @Test("nothing extra is imported when nothing is asked for")
    func noImportsByDefault() {
        let source = """
        @Injectable
        struct Stamp {
            @InjectableProviding
            init() {}
        }
        """

        let result = CompileFixture.generateWithResolution(source: source)

        #expect(result.output.output.hasPrefix("// Generated by Zerk\n// Do not change by hand.\n\nimport Zerk\n\n"))
    }

    @Test("a non-literal module name is not collected")
    func nonLiteralModuleIsNotCollected() {
        // The macro reports it; the plugin must not guess at it either.
        let collector = SourceCollector()
        collector.walk(Parser.parse(source: """
        let name = "Foundation"
        #ZerkImport(module: name)
        """))

        #expect(collector.importedModules.isEmpty)
    }

    @Test("an interpolated module name is not collected")
    func interpolatedModuleIsNotCollected() {
        let collector = SourceCollector()
        collector.walk(Parser.parse(source: """
        #ZerkImport(module: "Core\\(1)")
        """))

        #expect(collector.importedModules.isEmpty)
    }

    @Test("occurrences in different files all contribute")
    func occurrencesAcrossFilesAreUnioned() {
        // One collector walks every file in the module, so the set is the union.
        let collector = SourceCollector()
        collector.walk(Parser.parse(source: "#ZerkImport(module: \"Foundation\")"), path: "A.swift")
        collector.walk(Parser.parse(source: "#ZerkImport(module: \"CoreLocation\")"), path: "B.swift")

        #expect(collector.importedModules == ["Foundation", "CoreLocation"])
    }
}
