//
//  GeneratorOutputBuilder.swift
//  Zerk
//
//  Created by Ömer Faruk Gökce on 27.07.2026.
//

import Foundation

/// Turns resolved providers into the text of the generated file.
///
/// The last stage of the pipeline. For each key it emits an
/// `extension Zerk<Key>` holding one factory per provider — named after the
/// provider, so a key with several providers gets several members — plus a
/// single `inject()` entry point backed by the primary one. Alongside those go
/// the `@injected` overloads, the `Interjecting<Key>` protocols tests conform
/// to, and the `Sendable` checks singletons need.
///
/// Output is assembled as strings rather than syntax nodes, so nearly every
/// helper here returns a line or a fragment of one.
struct GeneratorOutputBuilder {
    let types: [TypeRecord]
    let values: [InjectableValueRecord]
    /// Every (key, provider) pair: one generated member each.
    let resolutions: [ProviderResolution]
    /// The provider backing `inject()` for each key, as elected by
    /// `ProviderResolver`. Everything resolved *implicitly* — a dependency
    /// parameter, an `@injected` argument, an `@Injected` property — goes
    /// through this rather than through `resolutions`, because those all call
    /// `inject()`.
    var primaryResolutions: [String: ProviderResolution] = [:]
    var moduleAccessLevels: [String: Bool] = [:]
    var injectedUses: [InjectedUseRecord] = []
    var markedMembers: [MarkedMemberRecord] = []
    /// Injectable key -> the spelling to emit for it, from `SourceCollector`.
    /// Absent keys are emitted as themselves.
    var keyDisplayNames: [String: String] = [:]

    /// How a key is written in the generated file.
    ///
    /// Differs from the key itself only in `any`: keys match with it stripped,
    /// because Zerk cannot tell an existential from a class, but the emitted
    /// spelling has to be the one the developer wrote.
    func displayName(for key: String) -> String {
        keyDisplayNames[key] ?? key
    }

    /// How to call a provider with its dependencies auto-resolved: the
    /// parameters a caller must still supply, the expressions to pass for all
    /// of them, and the effects the resulting call carries.
    struct WrapperPlan {
        let parameters: [ParameterRecord]
        let argumentExpressions: [String]
        let effects: ProviderEffects
        /// Bubbled requirements that clash with a parameter the provider already
        /// declares. Carried out rather than reported in place, because
        /// `wrapperPlan` runs many times per provider.
        var collisions: [BubbleResolver.Collision] = []
    }

    /// One `@Singleton`'s shared instance, as it appears in `_$zerk_singletons`.
    ///
    /// There is exactly one of these per singleton *type*, which is the whole
    /// point: storing it per key would give a type injectable under two keys two
    /// instances, and "singleton" would only hold within a key.
    struct SingletonStorage {
        let memberName: String
        let typeName: String
        let construction: String
        let isolation: ProviderIsolation
    }

    /// The name of the generated namespace holding every shared instance.
    ///
    /// File-private, and prefixed to stay out of the way of anything a developer
    /// might declare — the module's own code reaches these through `Zerk<Key>`,
    /// never directly.
    static let singletonStorageEnumName = "_$zerk_singletons"

    /// Rebuilt on each access rather than stored — it is a pure function of
    /// `values` and `primaryResolutions`, both of which are immutable here.
    private var classifier: ParameterClassifier {
        ParameterClassifier(values: values, primaryResolutions: primaryResolutions)
    }

    /// Emits the complete file.
    ///
    /// Diagnostics accumulate rather than short-circuit, so one run reports
    /// every problem in the module instead of only the first.
    func build() -> GeneratorOutput {
        var output: [String] = [
            "// Generated by Zerk",
            "// Do not change by hand.",
            "",
            "import Zerk",
            ""
        ]
        var diagnostics: [CodegenDiagnostic] = []
        var requirements: [InterjectionRequirement] = []
        var sendabilityChecks: [SendabilityCheck] = []
        var reportedAutoInjected = Set<String>()

        let classifier = self.classifier

        diagnostics += cycleDiagnostics()

        // Built up front: the storage is per type while the members reading it
        // are per key, so it cannot be assembled from inside the per-key loop.
        let singletonStorage = singletonStorage(diagnostics: &diagnostics)

        // @Injected expands to a synchronous, non-throwing accessor; a chain
        // containing an async or throwing provider — or one that crosses an
        // isolation domain, which becomes async — cannot be resolved by it.
        for use in injectedUses where !use.namesMemberDirectly {
            guard let unique = primaryResolutions[use.typeKey] else {
                continue
            }
            let plan = wrapperPlan(for: unique)
            if plan.effects.isAsync || plan.effects.isThrowing {
                diagnostics.append(CodegenDiagnostic(
                    severity: .error,
                    message: "'\(use.typeKey)' has an async, throwing, or cross-isolation dependency chain; \(use.macroName) cannot resolve it. Resolve manually with '\(plan.effects.callPrefix)Zerk<\(use.typeKey)>.inject()'.",
                    location: use.location
                ))
            }
        }

        let uniqueExternalSignatures = Set(primaryResolutions.values.map { macroSignatureKey(for: wrapperPlan(for: $0).parameters) })
            .sorted()

        output += generatedInjectedMacroDeclarations(for: uniqueExternalSignatures)

        if !uniqueExternalSignatures.isEmpty {
            output.append("")
        }

        var thunkLines: [String] = []
        var emittedThunks = Set<String>()

        for value in values.sorted(by: { $0.name < $1.name }) {
            let readExpression: String
            switch value.injectionMethod {
            case .copied:
                guard let bodyText = value.bodyText else {
                    diagnostics.append(CodegenDiagnostic(
                        severity: .error,
                        message: "Injectable value '\(value.name)' must define a body.",
                        location: value.location
                    ))
                    continue
                }
                readExpression = bodyText
            case .referenced:
                readExpression = referenceRead(for: value)
                // A value registered under several keys yields one record per
                // key, all naming the same source, so thunks dedupe by name.
                if emittedThunks.insert(value.name).inserted {
                    thunkLines += referenceThunkLines(for: value)
                }
            }

            let interjectedName = interjectedName(for: value.name)
            // Keyed on the canonical key, exactly as a type-backed member is.
            // Using the declared spelling instead would give a value registered
            // as `[String]` a different `Interjecting…` protocol from a type
            // registered as `Array<String>`, even though they are one key.
            let valueKeyText = value.keyText
            let guardLines = { (indent: String) in
                self.interjectionGuardLines(
                    protocolName: self.interjectingProtocolName(for: value.typeKey),
                    interjectedName: interjectedName,
                    callArguments: nil,
                    indent: indent
                )
            }

            output.append("extension Zerk<\(valueKeyText)> {")
            output.append("    \(value.isolation.declarationPrefix)static var \(value.name): \(valueKeyText) {")

            if value.injectionMethod == .referenced && value.isSettable {
                // Only a settable source earns a setter, and only then does the
                // member need an explicit accessor pair.
                output.append("        get {")
                output += guardLines("            ")
                output.append("            return \(readExpression)")
                output.append("        }")
                output.append("        set {")
                output.append("            \(referenceWrite(for: value, from: "newValue"))")
                output.append("        }")
            } else {
                output += guardLines("        ")
                output.append("        return \(readExpression)")
            }

            output.append("    }")
            output.append("}")
            output.append("")

            requirements.append(InterjectionRequirement(
                zerkArgument: value.typeKey,
                interjectedName: interjectedName,
                returnTypeName: valueKeyText,
                kind: .variable,
                isolation: value.isolation
            ))
        }

        if !thunkLines.isEmpty {
            output += thunkLines
            output.append("")
        }

        // Ahead of the extensions, which read from it.
        output += singletonStorageLines(singletonStorage)

        let grouped = Dictionary(grouping: resolutions, by: \.injectableKey)
        for injectableKey in grouped.keys.sorted() {
            let providers = grouped[injectableKey]!.sorted { lhs, rhs in
                memberName(for: lhs) < memberName(for: rhs)
            }

            // Keyed on name *and* parameter shape, because same-named members
            // are how multiple providers coexist: two marked initializers are
            // both named after their type, and generate overloads that Swift
            // tells apart exactly as it tells the initializers apart. Only an
            // identical shape is a genuine redeclaration.
            // A companion `var` can only exist where the member name is used
            // once: two providers sharing it are distinguished by their
            // parameters, which an argument-free `var` has none of.
            var memberNameCounts: [String: Int] = [:]
            for provider in providers {
                memberNameCounts[memberName(for: provider), default: 0] += 1
            }

            var seenMemberSignatures: [String: String] = [:]
            for provider in providers {
                let name = memberName(for: provider)
                for signature in memberSignatureKeys(for: provider, name: name) {
                    if let existing = seenMemberSignatures[signature] {
                        diagnostics.append(CodegenDiagnostic(
                            severity: .error,
                            message: "Generated member '\(name)' for '\(provider.typeName)' collides with '\(existing)' in Zerk<\(displayName(for: injectableKey))>: same name, same parameters. Rename the type, or give the provider a distinct @InjectableProviding function name.",
                            location: provider.provider.location
                        ))
                    } else {
                        seenMemberSignatures[signature] = provider.typeName
                    }
                }
            }

            output.append("extension Zerk<\(displayName(for: injectableKey))> {")

            for provider in providers {
                let classification = classifier.classify(provider)

                for collision in wrapperPlan(for: provider).collisions {
                    let identity = "collision|\(provider.typeName)|\(collision.own.name)|\(collision.requirement.typeKey)"
                    guard reportedAutoInjected.insert(identity).inserted else {
                        continue
                    }
                    diagnostics.append(CodegenDiagnostic(
                        severity: .error,
                        message: "Resolving '\(collision.dependencyName)' needs '\(collision.requirement.name): \(collision.requirement.typeName)', which collides with '\(provider.typeName)'s own '\(collision.own.name)' parameter. Mark it @injectable to feed the same value to both.",
                        location: collision.own.location ?? provider.provider.location
                    ))
                }

                // Deduped by parameter position: a provider serving two keys is
                // classified once per key, and the parameter is unresolvable in
                // both — but the developer wrote it once.
                for parameter in classification.unresolvedAutoInjected {
                    let identity = "\(provider.typeName)|\(parameter.name)|\(parameter.location.map(String.init(describing:)) ?? "")"
                    guard reportedAutoInjected.insert(identity).inserted else {
                        continue
                    }
                    diagnostics.append(CodegenDiagnostic(
                        severity: .error,
                        message: "@autoinjected parameter '\(parameter.name)' cannot be resolved: '\(parameter.typeKey)' is not injectable in this module. Declare it @Injectable, or drop @autoinjected and pass it in.",
                        location: parameter.location ?? provider.provider.location
                    ))
                }

                sendabilityChecks += classification.crossDomainSingletonDependencies.map {
                    SendabilityCheck(
                        singletonTypeName: $0,
                        consumerTypeName: provider.typeName,
                        consumerIsolation: provider.isolation
                    )
                }

                guard let lines = memberLines(
                    for: provider,
                    injectableKey: injectableKey,
                    classification: classification,
                    hasUniqueMemberName: memberNameCounts[memberName(for: provider)] == 1,
                    singletonStorage: singletonStorage,
                    requirements: &requirements,
                    diagnostics: &diagnostics
                ) else {
                    continue
                }

                output += lines
                output.append("")
            }

            if let primary = primaryResolutions[injectableKey] {
                output += injectLines(
                    for: primary,
                    injectableKey: injectableKey,
                    classification: classifier.classify(primary),
                    diagnostics: &diagnostics
                )
                output.append("")
            }

            output.append("}")
            output.append("")
        }

        output += markedMemberLines(diagnostics: &diagnostics)
        output += interjectionProtocolLines(requirements: requirements)
        output += sendabilityCheckLines(sendabilityChecks)

        return GeneratorOutput(
            output: output.joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines) + "\n",
            diagnostics: diagnostics,
            usesIsolatedDefaultArguments: resolutions.contains {
                classifier.classify($0).usesIsolatedDefaultArgument
            }
        )
    }

    // MARK: - Provider members

    /// Emits the member(s) for one provider.
    ///
    /// When every dependency is defaultable this is a single member, exactly as
    /// before. When at least one dependency has to be resolved in the body (an
    /// effectful or cross-domain resolution) it becomes two:
    ///
    /// - the **explicit** variant, taking those dependencies as required
    ///   parameters. It carries the interjection guard and the construction, so
    ///   there is exactly one of each per provider.
    /// - the **resolving** variant, which omits them, resolves them, and
    ///   delegates. It inherits the merged effects.
    ///
    /// Their arities always differ — the explicit variant's extra parameters are
    /// required — so the overload is never ambiguous.
    private func memberLines(for provider: ProviderResolution,
                             injectableKey: String,
                             classification: ProviderClassification,
                             hasUniqueMemberName: Bool,
                             singletonStorage: [String: SingletonStorage],
                             requirements: inout [InterjectionRequirement],
                             diagnostics: inout [CodegenDiagnostic]) -> [String]? {
        let memberName = memberName(for: provider)
        let isolation = provider.isolation
        let allParameters = provider.provider.parameters
        let ownEffects = provider.provider.effects
        let protocolName = interjectingProtocolName(for: injectableKey)
        let interjectedName = interjectedName(for: memberName)
        // The key as it is written in the output. The protocol name above stays
        // on the canonical key, so an `any` spelling cannot rename it.
        let keyText = displayName(for: injectableKey)

        if provider.isSingleton {
            // No entry means the shared instance had no legal form and the
            // reason was already reported against the type; emitting a member
            // that reads storage which does not exist would bury that behind a
            // compile error in generated code.
            guard let storage = singletonStorage[provider.typeName] else {
                return nil
            }
            requirements.append(InterjectionRequirement(
                zerkArgument: injectableKey,
                interjectedName: interjectedName,
                returnTypeName: keyText,
                kind: .variable,
                isolation: isolation
            ))
            return singletonLines(
                for: provider,
                injectableKey: injectableKey,
                memberName: memberName,
                protocolName: protocolName,
                interjectedName: interjectedName,
                storage: storage
            )
        }

        let defaults = classification.defaultExpressions
        let usesFunctionShape =
            !allParameters.isEmpty || ownEffects.isAsync || ownEffects.isThrowing

        var lines: [String] = []

        if usesFunctionShape {
            let signature = parameterClause(parameters: allParameters, defaults: defaults)
            let construction = "\(ownEffects.callPrefix)\(builderConstruction(for: provider))(\(builderArguments(allParameters, useParameterNames: true, defaults: defaults)))"
            lines.append("    \(isolation.declarationPrefix)static func \(memberName)\(signature)\(ownEffects.declarationSuffix) -> \(keyText) {")
            lines += interjectionGuardLines(
                protocolName: protocolName,
                interjectedName: interjectedName,
                callArguments: interjectedCallArguments(allParameters)
            )
            lines.append("        return \(construction)")
            lines.append("    }")

            requirements.append(InterjectionRequirement(
                zerkArgument: injectableKey,
                interjectedName: interjectedName,
                returnTypeName: keyText,
                kind: .function(parameters: allParameters),
                isolation: isolation
            ))

            if hasUniqueMemberName {
                lines += keyPathReachableVariantLines(
                    memberName: memberName,
                    keyText: keyText,
                    isolation: isolation,
                    ownEffects: ownEffects,
                    classification: classification
                )
            }
        } else {
            let construction = "\(ownEffects.callPrefix)\(builderConstruction(for: provider))()"
            lines.append("    \(isolation.declarationPrefix)static var \(memberName): \(keyText) {")
            lines += interjectionGuardLines(
                protocolName: protocolName,
                interjectedName: interjectedName,
                callArguments: nil
            )
            lines.append("        return \(construction)")
            lines.append("    }")

            requirements.append(InterjectionRequirement(
                zerkArgument: injectableKey,
                interjectedName: interjectedName,
                returnTypeName: keyText,
                kind: .variable,
                isolation: isolation
            ))
        }

        guard classification.requiresSplit else {
            return lines
        }

        // Resolving variant: same name, without the body-resolved parameters.
        let resolvingParameters = classification.resolvingVariantParameters
        let resolvingEffects = ownEffects.merged(with: classification.dependencyEffects)
        let resolvingSignature = parameterClause(parameters: resolvingParameters, defaults: defaults)
        let forwardedArguments = classification.parameters.map { classified -> String in
            let expression: String
            if case .bodyResolved(let resolved, _) = classified.binding {
                expression = resolved
            } else {
                expression = classified.parameter.name
            }
            if let label = classified.parameter.label {
                return "\(label): \(expression)"
            }
            return expression
        }
        .joined(separator: ", ")

        lines.append("")
        lines.append("    \(isolation.declarationPrefix)static func \(memberName)\(resolvingSignature)\(resolvingEffects.declarationSuffix) -> \(returnClause(for: provider, key: keyText, parameters: resolvingParameters, classification: classification)) {")
        lines.append("        \(ownEffects.callPrefix)\(memberName)(\(forwardedArguments))")
        lines.append("    }")

        return lines
    }

    /// Emits an argument-free `static var` alongside a function-shaped member
    /// whose parameters Zerk resolves in full.
    ///
    /// The function stays and keeps the construction and the interjection guard;
    /// this only delegates to it. That is what makes the pair legal — `live` and
    /// `live(dep:)` are different names, where `live` and `live()` would be a
    /// redeclaration — and it keeps one construction site, one guard and one
    /// interjection requirement.
    ///
    /// Its purpose is reach: `@Injected(\.live)` takes a key path, and a key path
    /// can name a property but not a method. The conditions below are exactly
    /// what makes such a property expressible:
    ///
    /// - **parameters, all resolvable** — with none the member is already a
    ///   `var`, and with an unresolvable one there is nothing to default it to.
    /// - **no effects, its own or its dependencies'** — Swift refuses to form a
    ///   key path to an `async` or `throws` property, so an effectful variant
    ///   could not be reached anyway; and for an argument-free effectful member
    ///   the two names would collide.
    private func keyPathReachableVariantLines(memberName: String,
                                              keyText: String,
                                              isolation: ProviderIsolation,
                                              ownEffects: ProviderEffects,
                                              classification: ProviderClassification) -> [String] {
        guard !classification.parameters.isEmpty,
              classification.isFullyResolvable,
              ownEffects == .none,
              classification.dependencyEffects == .none else {
            return []
        }

        return [
            "",
            "    \(isolation.declarationPrefix)static var \(memberName): \(keyText) {",
            "        \(memberName)()",
            "    }"
        ]
    }

    // MARK: - Singletons

    /// Builds the shared instance for every `@Singleton` in the module, keyed by
    /// the type that owns it.
    ///
    /// One entry per *type*, not per key. `Zerk<A>` and `Zerk<B>` are distinct
    /// generic specializations with distinct static storage, so a singleton
    /// stored on them directly would exist once per key — "singleton" would only
    /// hold within a key, which is not what the annotation says.
    ///
    /// Runs ahead of the per-key emission because the validation is per type
    /// too: checking inside the member loop would report the same unbuildable
    /// singleton once for every key it claims.
    private func singletonStorage(diagnostics: inout [CodegenDiagnostic]) -> [String: SingletonStorage] {
        var storage: [String: SingletonStorage] = [:]
        var attempted = Set<String>()
        var claimedNames: [String: String] = [:]
        let classifier = self.classifier

        // Sorted so the enum's members, and any diagnostic, land in the same
        // order on every build.
        let singletons = resolutions
            .filter(\.isSingleton)
            .sorted { ($0.typeName, $0.injectableKey) < ($1.typeName, $1.injectableKey) }

        for resolution in singletons {
            // The resolver has already proved every key of this type resolves to
            // the same provider, so the first one seen speaks for all of them.
            guard attempted.insert(resolution.typeName).inserted else {
                continue
            }
            guard let entry = singletonStorageEntry(
                for: resolution,
                classification: classifier.classify(resolution),
                diagnostics: &diagnostics
            ) else {
                continue
            }

            if let owner = claimedNames[entry.memberName] {
                diagnostics.append(CodegenDiagnostic(
                    severity: .error,
                    message: "@Singleton '\(resolution.typeName)' and '\(owner)' both store as '\(entry.memberName)' in \(Self.singletonStorageEnumName). Rename one of the types.",
                    location: resolution.provider.location
                ))
                continue
            }

            claimedNames[entry.memberName] = resolution.typeName
            storage[resolution.typeName] = entry
        }

        return storage
    }

    /// Validates one `@Singleton` and describes the storage to emit for it.
    ///
    /// Storage is initialized synchronously, which is why a singleton whose
    /// dependencies need `await` — including across an isolation hop — is
    /// reported as unbuildable rather than silently made async.
    private func singletonStorageEntry(for provider: ProviderResolution,
                                       classification: ProviderClassification,
                                       diagnostics: inout [CodegenDiagnostic]) -> SingletonStorage? {
        if !classification.isFullyResolvable {
            diagnostics.append(CodegenDiagnostic(
                severity: .error,
                message: "@Singleton injectables cannot accept external arguments.",
                location: provider.provider.location
            ))
            return nil
        }

        if provider.provider.effects.isAsync || provider.provider.effects.isThrowing {
            diagnostics.append(CodegenDiagnostic(
                severity: .error,
                message: "@Singleton providers cannot be async or throwing.",
                location: provider.provider.location
            ))
            return nil
        }

        // A `static let` initializer cannot `await`, and @Singleton is
        // synchronous by definition, so a dependency that has to be resolved in
        // the body has no legal generated form. This fires only when two
        // distinct domains collide: nonisolated dependencies reach an isolated
        // singleton for free.
        if classification.requiresSplit {
            let crossings = classification.bodyResolved.map(\.parameter.typeName).joined(separator: ", ")
            let reason = classification.hasIsolationCrossing
                ? "resolving '\(crossings)' crosses an isolation boundary, which requires 'await'"
                : "resolving '\(crossings)' is async or throwing"
            diagnostics.append(CodegenDiagnostic(
                severity: .error,
                message: "@Singleton '\(provider.typeName)' cannot be built: \(reason), but a singleton's storage is initialized synchronously. Make the dependency share '\(provider.typeName)'s isolation, or drop @Singleton and resolve it through inject().",
                location: provider.provider.location
            ))
            return nil
        }

        let defaults = classification.defaultExpressions

        return SingletonStorage(
            memberName: provider.typeName.lowerCamelCased,
            typeName: provider.singletonStorageTypeName,
            construction: "\(builderConstruction(for: provider))(\(builderArguments(provider.provider.parameters, useParameterNames: false, defaults: defaults)))",
            isolation: provider.isolation
        )
    }

    /// Emits the namespace holding every shared instance, or nothing when the
    /// module declares no singletons.
    private func singletonStorageLines(_ storage: [String: SingletonStorage]) -> [String] {
        guard !storage.isEmpty else {
            return []
        }

        var lines = ["private enum \(Self.singletonStorageEnumName) {"]

        for entry in storage.values.sorted(by: { $0.memberName < $1.memberName }) {
            switch entry.isolation {
            case .nonisolated:
                // `static let` initialization is thread-safe in the Swift
                // runtime; `nonisolated(unsafe)` acknowledges that sharing the
                // instance across isolation domains is the documented contract
                // of @Singleton (Swift 6 would otherwise require the stored type
                // to be Sendable).
                lines.append("    nonisolated(unsafe) static let \(entry.memberName): \(entry.typeName) = \(entry.construction)")
            case .globalActor(let name):
                // Global-actor isolation already protects the storage, so no
                // `nonisolated(unsafe)` escape hatch is needed here.
                lines.append("    @\(name) static let \(entry.memberName): \(entry.typeName) = \(entry.construction)")
            }
        }

        lines.append("}")
        lines.append("")
        return lines
    }

    /// Emits one key's view onto a shared instance: a getter reading the single
    /// entry in `_$zerk_singletons`.
    ///
    /// The interjection guard lives here rather than in the storage initializer,
    /// which it cannot: the guard is per key — `InterjectingA` and
    /// `InterjectingB` are different protocols — while the storage is per type.
    /// Consulting it on each read is the better semantics anyway: a test double
    /// installed after the first resolution now takes effect, and interjecting a
    /// singleton never builds the real instance at all.
    private func singletonLines(for provider: ProviderResolution,
                                injectableKey: String,
                                memberName: String,
                                protocolName: String,
                                interjectedName: String,
                                storage: SingletonStorage) -> [String] {
        var lines = [
            "    \(provider.isolation.declarationPrefix)static var \(memberName): \(displayName(for: injectableKey)) {"
        ]
        lines += interjectionGuardLines(
            protocolName: protocolName,
            interjectedName: interjectedName,
            callArguments: nil
        )
        lines.append("        return \(Self.singletonStorageEnumName).\(storage.memberName)")
        lines.append("    }")
        return lines
    }

    /// Where a `sending` return would go.
    ///
    /// `sending` would let a freshly constructed value leave the domain it was
    /// built in without its type having to be `Sendable`, which is the whole
    /// "it just works" story for cross-domain injection. It is **not emitted
    /// yet**, because making it sound requires changes that cannot be validated
    /// without compiling:
    ///
    /// - `sending` is not expressible on a property, so every isolated
    ///   argument-free provider would have to switch from a `var`-shaped member
    ///   to a function-shaped one — a visible API change that also reshapes the
    ///   interjection requirement.
    /// - the resolving variant delegates to the explicit variant, which takes
    ///   caller-supplied parameters and therefore cannot return `sending`. The
    ///   chain only holds if those parameters are themselves `sending`, which
    ///   constrains callers of the explicit variant.
    ///
    /// Emitting it speculatively across every isolated provider risks breaking
    /// the build everywhere at once, so the eligibility is computed and
    /// recorded here and the annotation is left off until the compile harness
    /// can confirm the exact shape. Until then, a value crossing a domain needs
    /// its key to be `Sendable` — which for `actor` and protocol-keyed
    /// injectables it usually already is.
    ///
    /// Deliberately uncalled today. `returnClause` is where it would be called
    /// from; keep the two signatures in step.
    func isSendingEligible(provider: ProviderResolution,
                           parameters: [ParameterRecord],
                           classification: ProviderClassification) -> Bool {
        parameters.isEmpty
            && !provider.isSingleton
            && provider.isolation.isGlobalActor
            && classification.singletonDependencies.isEmpty
    }

    // MARK: - Referenced values

    /// How a `.referenced` value reads its source.
    ///
    /// A member of a type is reached through that type. A *top-level*
    /// declaration cannot be named directly from inside `extension Zerk<T>`:
    /// the bare name resolves to the generated member itself, which compiles
    /// but recurses forever (the compiler only warns, "attempting to access
    /// within its own getter"). Routing it through a file-scope thunk fixes it,
    /// because file scope has no `Self` for the name to bind to.
    private func referenceRead(for value: InjectableValueRecord) -> String {
        guard let path = value.enclosingTypePath else {
            return "_$zerk_ref_\(value.name)()"
        }
        return "\(path).\(value.name)"
    }

    /// The mirror of `referenceRead` for assignment.
    private func referenceWrite(for value: InjectableValueRecord, from expression: String) -> String {
        guard let path = value.enclosingTypePath else {
            return "_$zerk_set_\(value.name)(\(expression))"
        }
        return "\(path).\(value.name) = \(expression)"
    }

    /// File-scope accessors for a top-level referenced value.
    ///
    /// They carry the value's isolation for the same reason generated members
    /// do — a nonisolated thunk cannot read `@MainActor` state. `nonisolated`
    /// is spelled as the absence of an attribute here, which is what a global
    /// function accepts.
    private func referenceThunkLines(for value: InjectableValueRecord) -> [String] {
        guard value.enclosingTypePath == nil else {
            return []
        }
        let prefix = value.isolation.actorName.map { "@\($0) " } ?? ""
        var lines = [
            "\(prefix)private func _$zerk_ref_\(value.name)() -> \(value.typeName) { \(value.name) }"
        ]
        if value.isSettable {
            lines.append(
                "\(prefix)private func _$zerk_set_\(value.name)(_ newValue: \(value.typeName)) { \(value.name) = newValue }"
            )
        }
        return lines
    }

    /// The generated member's return type: always the injectable key, so a type
    /// registered as `@Injectable<Storing>` returns `Storing` rather than its
    /// concrete type.
    ///
    /// The unused parameters are deliberate. They mirror `isSendingEligible`'s
    /// signature because this is the seam where a `sending` return would be
    /// applied — the body becomes a choice between `key` and `sending \(key)`,
    /// and both call sites already thread through exactly the arguments that
    /// decision needs. Dropping them would not simplify anything; it would move
    /// the work to whoever finishes `sending`.
    private func returnClause(for provider: ProviderResolution,
                              key: String,
                              parameters: [ParameterRecord],
                              classification: ProviderClassification) -> String {
        key
    }

    /// Emits `inject()`, the entry point every other generated member and every
    /// `@Injected` property calls.
    private func injectLines(for provider: ProviderResolution,
                             injectableKey: String,
                             classification: ProviderClassification,
                             diagnostics: inout [CodegenDiagnostic]) -> [String] {
        let plan = wrapperPlan(for: provider)
        let memberName = memberName(for: provider)
        let isolation = provider.isolation
        let memberIsCallable =
            !provider.isSingleton &&
            (!provider.provider.parameters.isEmpty ||
             provider.provider.effects.isAsync ||
             provider.provider.effects.isThrowing)

        var accessPrefix = provider.isShared ? "public " : ""
        if provider.isShared, moduleAccessLevels[injectableKey] == false {
            diagnostics.append(CodegenDiagnostic(
                severity: .warning,
                message: "@Shared has no effect: '\(injectableKey)' is not public, so the generated inject() cannot be public.",
                location: provider.provider.location
            ))
            accessPrefix = ""
        }

        let returns = returnClause(
            for: provider,
            key: displayName(for: injectableKey),
            parameters: plan.parameters,
            classification: classification
        )

        var lines: [String] = []
        if plan.parameters.isEmpty {
            // Nothing bubbles up, so the member can resolve everything itself:
            // call it bare and let its defaults (or, when the member split, its
            // resolving variant) do the work. `plan.effects` and the resolving
            // variant's effects agree here, because a defaulted dependency is
            // effect-free by construction.
            lines.append("    \(isolation.declarationPrefix)\(accessPrefix)static func inject()\(plan.effects.declarationSuffix) -> \(returns) {")
            if memberIsCallable {
                if isOverloaded(memberName, in: injectableKey) {
                    // Sibling providers share this name and are told apart by
                    // their parameters — but each one's parameters are fully
                    // defaulted, so a bare call matches every overload at once.
                    // Naming the arguments is what makes the call resolve; they
                    // are the same expressions the defaults hold.
                    lines.append("        \(provider.provider.effects.callPrefix)\(memberName)(\(memberCallArguments(for: provider, using: plan.argumentExpressions)))")
                } else {
                    lines.append("        \(plan.effects.callPrefix)\(memberName)()")
                }
            } else {
                lines.append("        \(memberName)")
            }
            lines.append("    }")
        } else {
            lines.append("    \(isolation.declarationPrefix)\(accessPrefix)static func inject\(parameterClause(parameters: plan.parameters, defaults: [:]))\(plan.effects.declarationSuffix) -> \(returns) {")
            lines.append("        \(provider.provider.effects.callPrefix)\(memberName)(\(memberCallArguments(for: provider, using: plan.argumentExpressions)))")
            lines.append("    }")
        }
        return lines
    }

    /// Re-declares the `@Injected` macro inside the generated file, one
    /// overload per distinct `inject()` signature, so a property can forward
    /// arguments through the attribute.
    private func generatedInjectedMacroDeclarations(for signatures: [String]) -> [String] {
        var lines = [
            [
                "@attached(peer, names: prefixed(_$zerk_injection_))",
                "macro Injected() = #externalMacro(module: \"ZerkMacros\", type: \"InjectedMacro\")"
            ],
            // Generic over the key, so one declaration serves every one of them —
            // unlike the argument-forwarding overloads, whose labels differ per
            // provider.
            [
                "@attached(peer, names: prefixed(_$zerk_injection_))",
                "macro Injected<T>(_ keyPath: KeyPath<Zerk<T>.Type, T>) = #externalMacro(module: \"ZerkMacros\", type: \"InjectedMacro\")"
            ]
        ]

        for signature in signatures where !signature.isEmpty {
            lines.append(
                [
                    "@attached(peer, names: prefixed(_$zerk_injection_))",
                    "macro Injected\(signature) = #externalMacro(module: \"ZerkMacros\", type: \"InjectedMacro\")"
                ]
            )
        }

        return lines
            .joined(separator: [""])
            .map { $0 }
    }

    /// Emits per-type extensions containing overloads of members with
    /// `@injected` parameters: each marked parameter is omitted from the
    /// overload and filled via the resolved `Zerk<T>` member; unmarked
    /// parameters pass through unchanged. Effects of resolved chains merge
    /// into the overload (an async chain yields an async overload), and a
    /// dependency in another isolation domain merges in as `async` too.
    private func markedMemberLines(diagnostics: inout [CodegenDiagnostic]) -> [String] {
        guard !markedMembers.isEmpty else {
            return []
        }

        var lines: [String] = []
        var seenOverloads = Set<String>()

        let grouped = Dictionary(grouping: markedMembers, by: \.typeName)
        for typeName in grouped.keys.sorted() {
            var memberLines: [String] = []

            for record in grouped[typeName]! {
                var argumentExpressions: [String] = []
                var overloadParameterParts: [String] = []
                var requests: [BubbleResolver.Request] = []
                var dependencyCalls: [String: (prefix: String, key: String, label: String?)] = [:]
                var effects = record.effects
                var failed = false

                // The member's own parameters, indexed for the bubbling step. An
                // @injected parameter is resolved rather than passed in, so it
                // cannot feed anything and is excluded.
                let ownParameters = Dictionary(
                    record.parameters
                        .filter { !$0.isMarked }
                        .map { ($0.parameter.resolutionIdentity, $0.parameter) },
                    uniquingKeysWith: { first, _ in first }
                )

                for markedParameter in record.parameters {
                    let core = markedParameter.parameter

                    guard markedParameter.isMarked else {
                        let label = core.label ?? "_"
                        var part = label == core.name
                            ? "\(label): \(core.typeName)"
                            : "\(label) \(core.name): \(core.typeName)"
                        if let defaultText = markedParameter.defaultText {
                            part += " = \(defaultText)"
                        }
                        overloadParameterParts.append(part)
                        argumentExpressions.append(overloadArgument(label: core.label, expression: core.name))
                        continue
                    }

                    if let value = classifier.injectableValue(matching: core) {
                        let hops = value.isolation.requiresHop(callingFrom: record.isolation.dependencyCallContext)
                        let callEffects = ProviderEffects(isAsync: hops, isThrowing: false)
                        effects = effects.merged(with: callEffects)
                        argumentExpressions.append(
                            overloadArgument(
                                label: core.label,
                                expression: "\(callEffects.callPrefix)Zerk<\(value.keyText)>.\(value.name)"
                            )
                        )
                        continue
                    }

                    if let unique = primaryResolutions[core.typeKey] {
                        let plan = wrapperPlan(for: unique)
                        let hops = unique.isolation.requiresHop(callingFrom: record.isolation.dependencyCallContext)
                        let callEffects = plan.effects
                            .merged(with: ProviderEffects(isAsync: hops, isThrowing: false))
                        effects = effects.merged(with: callEffects)

                        // Deferred: what each dependency is called with depends
                        // on how *every* dependency's requirements fold together.
                        requests.append(BubbleResolver.Request(
                            sourceName: core.name,
                            requirements: plan.parameters
                        ))
                        dependencyCalls[core.name] = (callEffects.callPrefix, core.typeName, core.label)
                        argumentExpressions.append("\u{0}\(core.name)")
                        continue
                    }

                    diagnostics.append(CodegenDiagnostic(
                        severity: .error,
                        message: "@injected parameter '\(core.name)': '\(core.typeKey)' is not injectable in this module. Declare it @Injectable, or remove @injected.",
                        location: record.location
                    ))
                    failed = true
                    break
                }

                if failed {
                    continue
                }

                let bubble = BubbleResolver.resolve(requests, ownExternals: ownParameters)

                for collision in bubble.collisions {
                    diagnostics.append(CodegenDiagnostic(
                        severity: .error,
                        message: "Resolving @injected parameter '\(collision.dependencyName)' needs '\(collision.requirement.name): \(collision.requirement.typeName)', which collides with this member's own '\(collision.own.name)' parameter. Mark it @injectable to feed the same value to both.",
                        location: collision.own.location ?? record.location
                    ))
                }
                if !bubble.collisions.isEmpty {
                    continue
                }

                // Bubbled parameters go after the member's own, in the order
                // their sources appear.
                overloadParameterParts += bubble.parameters.map { parameter in
                    let label = parameter.label ?? "_"
                    return label == parameter.name
                        ? "\(label): \(parameter.typeName)"
                        : "\(label) \(parameter.name): \(parameter.typeName)"
                }

                argumentExpressions = argumentExpressions.map { expression in
                    guard expression.hasPrefix("\u{0}") else {
                        return expression
                    }
                    let source = String(expression.dropFirst())
                    let call = dependencyCalls[source]!
                    let arguments = bubble.arguments[source] ?? []
                    let resolved = arguments.isEmpty
                        ? "\(call.prefix)Zerk<\(call.key)>.inject()"
                        : "\(call.prefix)Zerk<\(call.key)>.inject(\(arguments.joined(separator: ", ")))"
                    return overloadArgument(label: call.label, expression: resolved)
                }

                let accessPrefix = record.isPublic ? "public " : ""
                let isolationPrefix = record.isolation.declarationPrefix
                let signature = "(\(overloadParameterParts.joined(separator: ", ")))"
                let callArguments = argumentExpressions.joined(separator: ", ")

                let overloadKey: String
                let declarationLines: [String]

                switch record.kind {
                case .initializer:
                    let keyword = record.typeKind == .classKind ? "convenience init" : "init"
                    overloadKey = "\(typeName).init\(signature)"
                    declarationLines = [
                        "    \(isolationPrefix)\(accessPrefix)\(keyword)\(signature)\(effects.declarationSuffix) {",
                        "        \(record.effects.callPrefix)self.init(\(callArguments))",
                        "    }"
                    ]
                case .method(let name, let isStatic, let returnType):
                    let staticPrefix = isStatic ? "static " : ""
                    let returnSuffix = returnType.map { " -> \($0)" } ?? ""
                    overloadKey = "\(typeName).\(staticPrefix)\(name)\(signature)"
                    declarationLines = [
                        "    \(isolationPrefix)\(accessPrefix)\(staticPrefix)func \(name)\(signature)\(effects.declarationSuffix)\(returnSuffix) {",
                        "        \(record.effects.callPrefix)\(name)(\(callArguments))",
                        "    }"
                    ]
                }

                if !seenOverloads.insert(overloadKey).inserted {
                    diagnostics.append(CodegenDiagnostic(
                        severity: .error,
                        message: "Two @injected members of '\(typeName)' generate the same overload \(overloadKey). Differentiate the remaining parameters.",
                        location: record.location
                    ))
                    continue
                }

                memberLines.append(contentsOf: declarationLines)
                memberLines.append("")
            }

            if !memberLines.isEmpty {
                lines.append("extension \(typeName) {")
                lines.append(contentsOf: memberLines.dropLast())
                lines.append("}")
                lines.append("")
            }
        }

        return lines
    }

    /// One argument of a generated call, with its label restored when it has
    /// one.
    private func overloadArgument(label: String?, expression: String) -> String {
        label.map { "\($0): \(expression)" } ?? expression
    }

    /// Detects circular dependencies in the resolution graph up front, so the
    /// classifier's recursion guard never degrades silently. Edges mirror the
    /// classifier's resolution rules: injectable values shadow providers, and
    /// an edge exists only where the dependency resolves through `inject()`.
    ///
    /// Non-primary providers contribute no edges. They are never resolved on
    /// anyone's behalf, so a cycle through one is not a cycle Zerk can walk into
    /// — the caller has to name that member itself.
    private func cycleDiagnostics() -> [CodegenDiagnostic] {
        let classifier = self.classifier

        var edges: [String: [String]] = [:]
        for (key, resolution) in primaryResolutions {
            for parameter in resolution.provider.parameters {
                if classifier.injectableValue(matching: parameter) != nil {
                    continue
                }
                if primaryResolutions[parameter.typeKey] != nil {
                    edges[key, default: []].append(parameter.typeKey)
                }
            }
        }

        var diagnostics: [CodegenDiagnostic] = []
        var reportedCycles = Set<String>()
        var finished = Set<String>()

        func visit(_ node: String, path: [String]) {
            if let startIndex = path.firstIndex(of: node) {
                let cycle = Array(path[startIndex...]) + [node]
                let canonical = cycle.dropLast().sorted().joined(separator: "|")
                if reportedCycles.insert(canonical).inserted,
                   let location = primaryResolutions[node]?.provider.location {
                    diagnostics.append(CodegenDiagnostic(
                        severity: .error,
                        message: "Circular dependency detected: \(cycle.joined(separator: " -> ")). Break the cycle by removing one dependency.",
                        location: location
                    ))
                }
                return
            }
            if finished.contains(node) {
                return
            }
            for next in edges[node] ?? [] {
                visit(next, path: path + [node])
            }
            finished.insert(node)
        }

        for node in edges.keys.sorted() {
            visit(node, path: [])
        }

        return diagnostics
    }

    /// The generated factory's name: a static factory keeps its own name, while
    /// an initializer-backed provider is named after its type, lowercased.
    private func memberName(for resolution: ProviderResolution) -> String {
        resolution.provider.memberNameHint ?? resolution.typeName.lowerCamelCased
    }

    /// Whether more than one provider for this key generates a member of this
    /// name — i.e. whether the name is an overload set rather than a single
    /// member. Two of a type's initializers are the usual way this happens.
    private func isOverloaded(_ name: String, in injectableKey: String) -> Bool {
        resolutions.filter {
            $0.injectableKey == injectableKey && memberName(for: $0) == name
        }
        .count > 1
    }

    /// Every signature the member(s) generated for one provider will occupy.
    ///
    /// Two of a type's initializers are both named after that type, so their
    /// members share a name and are told apart by their parameters — exactly as
    /// the initializers themselves are. Sharing a name is therefore not a
    /// collision; sharing a name *and* a parameter list is.
    ///
    /// A provider yields two signatures when its dependencies split it, since
    /// both variants carry the same name. A property-shaped member is keyed as
    /// taking no parameters, which is conservative: Swift will not accept a
    /// `var` alongside an argument-free `func` of the same name either.
    private func memberSignatureKeys(for provider: ProviderResolution, name: String) -> [String] {
        guard !provider.isSingleton else {
            return ["\(name)()"]
        }

        let parameters = provider.provider.parameters
        let effects = provider.provider.effects
        guard !parameters.isEmpty || effects.isAsync || effects.isThrowing else {
            return ["\(name)()"]
        }

        var keys = ["\(name)\(protocolParameterClause(parameters))"]

        let classification = classifier.classify(provider)
        if classification.requiresSplit {
            keys.append("\(name)\(protocolParameterClause(classification.resolvingVariantParameters))")
        }
        return keys
    }

    /// Renders a parameter list, attaching a default value to each parameter
    /// the classifier put in the **S** partition.
    private func parameterClause(parameters: [ParameterRecord], defaults: [String: String]) -> String {
        let parts = parameters.map { parameter in
            let label = renderedLabel(for: parameter)
            if let defaultValue = defaults[parameter.name] {
                if label == parameter.name {
                    return "\(label): \(parameter.typeName) = \(defaultValue)"
                }
                return "\(label) \(parameter.name): \(parameter.typeName) = \(defaultValue)"
            }
            if label == parameter.name {
                return "\(label): \(parameter.typeName)"
            }
            return "\(label) \(parameter.name): \(parameter.typeName)"
        }
        return "(\(parts.joined(separator: ", ")) )".replacingOccurrences(of: " )", with: ")")
    }

    /// Forwards a parameter to an inner call by name, keeping its label.
    private func callArgument(for parameter: ParameterRecord) -> String {
        if let label = parameter.label {
            return "\(label): \(parameter.name)"
        }
        return parameter.name
    }

    /// The label as written, or `_` for a parameter declared without one.
    private func renderedLabel(for parameter: ParameterRecord) -> String {
        parameter.label ?? "_"
    }

    // MARK: - Interjection

    /// Emits the interjection guard that opens every generated member body:
    /// if `Zerk<Key>` conforms to the matching `Interjecting<Key>` protocol and
    /// the mirrored member returns a value, that value is used instead of the
    /// real provider. `callArguments` is `nil` for property-shaped members and
    /// the (possibly empty) argument list for function-shaped members.
    private func interjectionGuardLines(protocolName: String,
                                       interjectedName: String,
                                       callArguments: String?,
                                       indent: String = "        ") -> [String] {
        let access = callArguments.map { "\(interjectedName)(\($0))" } ?? interjectedName
        return [
            "\(indent)if let interjector = Self.self as? any \(protocolName).Type,",
            "\(indent)    let interjected = interjector.\(access) {",
            "\(indent)    return interjected",
            "\(indent)}"
        ]
    }

    /// The expression that constructs the real implementation, e.g. `Logger`
    /// for an initializer provider or `LiveUserService.live` for a static one.
    private func builderConstruction(for resolution: ProviderResolution) -> String {
        switch resolution.provider {
        case .explicit(let provider):
            switch provider.kind {
            case .initializer:
                return resolution.typeName
            case .staticFunction(let name):
                return "\(resolution.typeName).\(name)"
            }
        case .implicit:
            return resolution.typeName
        }
    }

    /// Labeled arguments passed to the real builder. Function-shaped members
    /// forward their own parameter names (which carry resolved defaults);
    /// property-shaped members inline the resolved default expressions.
    private func builderArguments(_ parameters: [ParameterRecord],
                                  useParameterNames: Bool,
                                  defaults: [String: String]) -> String {
        parameters.map { parameter in
            let value = useParameterNames ? parameter.name : (defaults[parameter.name] ?? parameter.name)
            if let label = parameter.label {
                return "\(label): \(value)"
            }
            return value
        }
        .joined(separator: ", ")
    }

    /// Labeled arguments forwarded to the mirrored interjection member, using
    /// the enclosing member's parameter names.
    private func interjectedCallArguments(_ parameters: [ParameterRecord]) -> String {
        parameters.map { parameter in
            if let label = parameter.label {
                return "\(label): \(parameter.name)"
            }
            return parameter.name
        }
        .joined(separator: ", ")
    }

    /// The interjection requirement mirroring a generated member: `live`
    /// becomes `interjectedLive`.
    private func interjectedName(for memberName: String) -> String {
        "interjected" + upperFirst(memberName)
    }

    /// `Interjecting` plus the key rendered as an identifier, e.g.
    /// `InterjectingStoring`.
    private func interjectingProtocolName(for key: String) -> String {
        "Interjecting" + sanitizedIdentifier(key)
    }

    /// Uppercases the first character only, leaving the rest as written.
    private func upperFirst(_ string: String) -> String {
        guard let first = string.first else {
            return string
        }
        return first.uppercased() + string.dropFirst()
    }

    /// Reduces a type key to characters legal in an identifier, so keys like
    /// `[String]` or `any Storing` can still name a generated protocol or
    /// function.
    private func sanitizedIdentifier(_ key: String) -> String {
        let scalars = key.unicodeScalars.filter {
            CharacterSet.alphanumerics.contains($0) || $0 == "_"
        }
        return String(String.UnicodeScalarView(scalars))
    }

    /// Emits one `Interjecting<Key>` protocol per injectable key, gathering the
    /// requirements contributed by that key's members. Developers conform
    /// `Zerk<Key>` to these protocols in their test suites to override members.
    ///
    /// Requirements mirror the isolation of the member they stand in for: a
    /// generated member cannot call a requirement that lives in another domain.
    private func interjectionProtocolLines(requirements: [InterjectionRequirement]) -> [String] {
        guard !requirements.isEmpty else {
            return []
        }

        var lines: [String] = []
        let grouped = Dictionary(grouping: requirements, by: \.zerkArgument)

        for zerkArgument in grouped.keys.sorted() {
            // Deduped by name *and* parameters, not by name alone: several
            // providers for one key can share a member name, and each overload
            // needs its own requirement. Collapsing them would leave a generated
            // member calling a requirement that was never declared.
            let sorted = grouped[zerkArgument]!.sorted { identity(of: $0) < identity(of: $1) }
            var seen = Set<String>()

            lines.append("protocol \(interjectingProtocolName(for: zerkArgument)) {")
            for requirement in sorted {
                guard seen.insert(identity(of: requirement)).inserted else {
                    continue
                }
                // Isolation comes first: `@MainActor static var` is the valid
                // ordering for an attribute, and `nonisolated static var` the
                // conventional one for a modifier.
                let isolation = requirement.isolation.declarationPrefix
                switch requirement.kind {
                case .variable:
                    lines.append("    \(isolation)static var \(requirement.interjectedName): \(optionalOf(requirement.returnTypeName)) { get }")
                case .function(let parameters):
                    lines.append("    \(isolation)static func \(requirement.interjectedName)\(protocolParameterClause(parameters)) -> \(optionalOf(requirement.returnTypeName))")
                }
            }
            lines.append("}")
            lines.append("")
        }

        return lines
    }

    /// What makes two interjection requirements the same requirement: the
    /// mirrored member's name together with its parameters.
    private func identity(of requirement: InterjectionRequirement) -> String {
        switch requirement.kind {
        case .variable:
            return requirement.interjectedName
        case .function(let parameters):
            return requirement.interjectedName + protocolParameterClause(parameters)
        }
    }

    /// Makes a type optional, parenthesizing it when `?` would otherwise bind to
    /// the wrong thing.
    ///
    /// `any Serving?` is a parse error — Swift reads it as `any (Serving?)` and
    /// asks for `(any Serving)?`. The same goes for a composition (`A & B?`) and
    /// a function type. A plain identifier, generic or not, needs no help, and
    /// `Dictionary<String, Int>?` is already unambiguous because the space is
    /// inside the brackets.
    private func optionalOf(_ typeText: String) -> String {
        hasTopLevelBreak(typeText) ? "(\(typeText))?" : "\(typeText)?"
    }

    /// Whether the spelling has a space or `&` outside any bracket, which is
    /// what makes a trailing `?` ambiguous.
    private func hasTopLevelBreak(_ text: String) -> Bool {
        var depth = 0
        for character in text {
            switch character {
            case "<", "(", "[":
                depth += 1
            case ">", ")", "]":
                depth = max(0, depth - 1)
            case " ", "&":
                if depth == 0 {
                    return true
                }
            default:
                break
            }
        }
        return false
    }

    /// Like `parameterClause`, minus defaults: a protocol requirement cannot
    /// declare them.
    private func protocolParameterClause(_ parameters: [ParameterRecord]) -> String {
        let parts = parameters.map { parameter -> String in
            let label = parameter.label ?? "_"
            if label == parameter.name {
                return "\(label): \(parameter.typeName)"
            }
            return "\(label) \(parameter.name): \(parameter.typeName)"
        }
        return "(\(parts.joined(separator: ", ")))"
    }

    // MARK: - Sendability

    /// One "this singleton is reached from that consumer" pair.
    ///
    /// Equality and hashing deliberately ignore `consumerIsolation`: which
    /// check to emit is decided by the singleton/consumer pair alone, and the
    /// isolation only decorates the generated comment. Including it would emit
    /// near-duplicate checks for a single logical crossing.
    private struct SendabilityCheck: Hashable {
        let singletonTypeName: String
        let consumerTypeName: String
        let consumerIsolation: ProviderIsolation

        static func == (lhs: SendabilityCheck, rhs: SendabilityCheck) -> Bool {
            lhs.singletonTypeName == rhs.singletonTypeName
                && lhs.consumerTypeName == rhs.consumerTypeName
        }

        func hash(into hasher: inout Hasher) {
            hasher.combine(singletonTypeName)
            hasher.combine(consumerTypeName)
        }
    }

    /// Zerk cannot prove `Sendable` from syntax, and does not try. The check
    /// costs nothing when the type already conforms, so it is emitted
    /// unconditionally wherever a singleton crosses an isolation boundary and
    /// the compiler is left to decide — with the failure landing on a line
    /// carrying an explanation rather than deep inside a factory body.
    private func sendabilityCheckLines(_ checks: [SendabilityCheck]) -> [String] {
        let unique = Array(Set(checks)).sorted {
            ($0.singletonTypeName, $0.consumerTypeName) < ($1.singletonTypeName, $1.consumerTypeName)
        }
        guard !unique.isEmpty else {
            return []
        }

        var lines = [
            "private func _$zerk_sendable_conformance_check<T: Sendable>(_: T.Type) {}",
            ""
        ]

        for check in unique {
            let domain = check.consumerIsolation.actorName.map { "'\($0)'-isolated " } ?? ""
            lines.append("private func _$zerk_sendable_conformance_check_\(sanitizedIdentifier(check.singletonTypeName))_in_\(sanitizedIdentifier(check.consumerTypeName))() {")
            lines.append("    // '@Singleton \(check.singletonTypeName)' is injected into \(domain)'\(check.consumerTypeName)'.")
            lines.append("    // Singletons that cross isolation domains must be Sendable.")
            lines.append("    _$zerk_sendable_conformance_check(\(check.singletonTypeName).self)")
            lines.append("}")
            lines.append("")
        }

        return lines
    }

    // MARK: - inject() flattening

    /// Identifies an `inject()` overload by parameter shape, so the generated
    /// `@Injected` macro declarations are emitted once per distinct signature
    /// rather than once per provider.
    private func macroSignatureKey(for parameters: [ParameterRecord]) -> String {
        guard !parameters.isEmpty else {
            return ""
        }
        let parts = parameters.map { parameter in
            let label = parameter.label ?? "_"
            return "\(label): \(parameter.typeName)"
        }
        return "(\(parts.joined(separator: ", ")))"
    }

    /// Flattens a provider's whole dependency subtree into a single `inject()`
    /// signature: every parameter that cannot be resolved anywhere in the tree
    /// bubbles up, and everything else is inlined as an expression.
    ///
    /// This is deliberately different from the E/S/A classification, which only
    /// looks one level down to decide what a *named member* exposes.
    private func wrapperPlan(for resolution: ProviderResolution,
                             visiting: Set<String> = []) -> WrapperPlan {
        let resolutionKey = "\(resolution.injectableKey)|\(resolution.typeName)"
        if visiting.contains(resolutionKey) {
            return WrapperPlan(
                parameters: resolution.provider.parameters,
                argumentExpressions: resolution.provider.parameters.map(callArgument),
                effects: resolution.provider.effects
            )
        }

        let nextVisiting = visiting.union([resolutionKey])
        let memberIsolation = resolution.isolation
        let classifier = self.classifier

        var ownParameters: [ParameterRecord] = []
        var argumentExpressions: [String] = []
        var effects = resolution.provider.effects
        // Gathered first, resolved together: sharing and disambiguation are
        // decisions about the whole set, not about one dependency at a time.
        var requests: [BubbleResolver.Request] = []
        var dependencyCalls: [String: (prefix: String, key: String)] = [:]

        // Explicit mode applies here too. `inject()` flattens the whole subtree,
        // so without this an unmarked parameter would still be resolved behind
        // the caller's back — the exact thing marking asks Zerk not to do.
        let isExplicit = resolution.provider.parameters.contains(where: \.isAutoInjected)

        // Which parameters this provider exposes itself, computed up front: a
        // dependency may bubble a requirement before the parameter that would
        // feed it has been reached. Mirrors the branches of the loop below.
        var ownExternals: [String: ParameterRecord] = [:]
        for parameter in resolution.provider.parameters {
            let staysExternal: Bool
            if isExplicit ? !parameter.isAutoInjected : parameter.isNonInjected {
                staysExternal = true
            } else if classifier.injectableValue(matching: parameter) != nil {
                staysExternal = false
            } else if primaryResolutions[parameter.typeKey] != nil {
                staysExternal = false
            } else {
                staysExternal = true
            }
            if staysExternal {
                ownExternals[parameter.resolutionIdentity] = parameter
            }
        }

        for parameter in resolution.provider.parameters {
            if isExplicit ? !parameter.isAutoInjected : parameter.isNonInjected {
                ownParameters = mergeParameters(ownParameters, with: [parameter])
                argumentExpressions.append(parameter.name)
                continue
            }

            if let value = classifier.injectableValue(matching: parameter) {
                let hops = value.isolation.requiresHop(callingFrom: memberIsolation)
                let callEffects = ProviderEffects(isAsync: hops, isThrowing: false)
                effects = effects.merged(with: callEffects)
                argumentExpressions.append("\(callEffects.callPrefix)Zerk<\(value.keyText)>.\(value.name)")
                continue
            }

            if let dependency = primaryResolutions[parameter.typeKey] {
                let dependencyPlan = wrapperPlan(for: dependency, visiting: nextVisiting)
                let hops = dependency.isolation.requiresHop(callingFrom: memberIsolation)
                let callEffects = dependencyPlan.effects
                    .merged(with: ProviderEffects(isAsync: hops, isThrowing: false))
                effects = effects.merged(with: callEffects)

                // Placeholder: the call cannot be written until every
                // dependency's requirements have been folded together.
                requests.append(BubbleResolver.Request(
                    sourceName: parameter.name,
                    requirements: dependencyPlan.parameters
                ))
                dependencyCalls[parameter.name] = (callEffects.callPrefix, parameter.typeName)
                argumentExpressions.append("\u{0}\(parameter.name)")
                continue
            }

            ownParameters = mergeParameters(ownParameters, with: [parameter])
            argumentExpressions.append(parameter.name)
        }

        let bubble = BubbleResolver.resolve(requests, ownExternals: ownExternals)

        // Bubbled parameters go after the provider's own, in the order their
        // sources appear — the same shape the @injected overload uses.
        return WrapperPlan(
            parameters: ownParameters + bubble.parameters,
            argumentExpressions: argumentExpressions.map { expression in
                guard expression.hasPrefix("\u{0}") else {
                    return expression
                }
                let source = String(expression.dropFirst())
                let call = dependencyCalls[source]!
                let arguments = bubble.arguments[source] ?? []
                return arguments.isEmpty
                    ? "\(call.prefix)Zerk<\(call.key)>.inject()"
                    : "\(call.prefix)Zerk<\(call.key)>.inject(\(arguments.joined(separator: ", ")))"
            },
            effects: effects,
            collisions: bubble.collisions
        )
    }

    /// Unions parameter lists in order, dropping exact duplicates: two
    /// dependencies may need the same caller-supplied parameter, which must
    /// still appear once in the generated signature.
    private func mergeParameters(_ existing: [ParameterRecord], with newParameters: [ParameterRecord]) -> [ParameterRecord] {
        var merged = existing
        var seen = Set(existing.map(parameterIdentity))

        for parameter in newParameters {
            let identity = parameterIdentity(parameter)
            if seen.insert(identity).inserted {
                merged.append(parameter)
            }
        }

        return merged
    }

    /// Deduplication identity: label, name, and type together. Parameters
    /// agreeing on all three are interchangeable at the call site.
    private func parameterIdentity(_ parameter: ParameterRecord) -> String {
        "\(parameter.label ?? "_")|\(parameter.name)|\(parameter.typeKey)|\(parameter.typeName)"
    }

    /// Pairs a provider's parameters with their resolved expressions,
    /// restoring argument labels.
    private func memberCallArguments(for resolution: ProviderResolution, using expressions: [String]) -> String {
        zip(resolution.provider.parameters, expressions)
            .map { parameter, expression in
                if let label = parameter.label {
                    return "\(label): \(expression)"
                }
                return expression
            }
            .joined(separator: ", ")
    }
}
